CREATE INDEX IF NOT EXISTS "Contract_tenantId_idx" ON "Contract" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Contract_roomId_idx" ON "Contract" USING btree ("roomId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Expense_landlordId_idx" ON "Expense" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Expense_propertyId_idx" ON "Expense" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "InvoiceItem_invoiceId_idx" ON "InvoiceItem" USING btree ("invoiceId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Invoice_roomId_idx" ON "Invoice" USING btree ("roomId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Invoice_payosOrderCode_idx" ON "Invoice" USING btree ("payosOrderCode");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Invoice_payosPaymentLinkId_idx" ON "Invoice" USING btree ("payosPaymentLinkId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "MaintenanceRequest_tenantId_idx" ON "MaintenanceRequest" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "MaintenanceRequest_assignedToId_idx" ON "MaintenanceRequest" USING btree ("assignedToId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "MeterReading_roomId_idx" ON "MeterReading" USING btree ("roomId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "MeterReading_room_service_month_idx" ON "MeterReading" USING btree ("roomId","serviceId","month");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "NotificationQueue_landlordId_idx" ON "NotificationQueue" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "NotificationQueue_status_idx" ON "NotificationQueue" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "PaymentTransaction_providerTransactionId_idx" ON "PaymentTransaction" USING btree ("providerTransactionId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "PaymentTransaction_landlordId_idx" ON "PaymentTransaction" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "PaymentTransaction_invoiceId_idx" ON "PaymentTransaction" USING btree ("invoiceId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Property_landlordId_idx" ON "Property" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "RoomServiceConfig_roomId_idx" ON "RoomServiceConfig" USING btree ("roomId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "RoomServiceConfig_serviceId_idx" ON "RoomServiceConfig" USING btree ("serviceId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Room_propertyId_idx" ON "Room" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Room_tenantId_idx" ON "Room" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "Service_landlordId_idx" ON "Service" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "SubscriptionChangeRequest_landlordId_idx" ON "SubscriptionChangeRequest" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "SubscriptionChangeRequest_status_idx" ON "SubscriptionChangeRequest" USING btree ("status");